#!/bin/bash

if [ $1 == "configure" ]; then

	update-rc.d sickbeard defaults &>/dev/null

	if [ ! -d "/home/xbian/downloads" ]; then
		mkdir -p /home/xbian/downloads
	fi

	chmod 777 /home/xbian/downloads
	chown xbian:xbian /home/xbian/downloads

	if [ ! -d "/home/xbian/incomplete" ]; then
		mkdir -p /home/xbian/incomplete
	fi

	chmod 777 /home/xbian/incomplete
	chown xbian:xbian /home/xbian/incomplete

	if [ ! -d "/home/xbian/torrents" ]; then
		mkdir -p /home/xbian/torrents
	fi

	chmod 777 /home/xbian/torrents
	chown xbian:xbian /home/xbian/torrents

	if [ -f "/usr/local/etc/sickbeard/sickbeard.reuse" ]; then
		mv /usr/local/etc/sickbeard/sickbeard.ini /usr/local/etc/sickbeard/sickbeard.new;
		mv /usr/local/etc/sickbeard/sickbeard.reuse /usr/local/etc/sickbeard/sickbeard.ini;
	fi

	chmod 777 /usr/local/share/sickbeard
	chown -R xbian /usr/local/share/sickbeard
	chmod -R 777 /usr/local/etc/sickbeard


	/etc/init.d/sickbeard start &>/dev/null

fi
