#!/bin/bash

if [ $1 == "install" -o $1 == "upgrade" ]; then

	 if [ -f "/usr/local/etc/sickbeard/sickbeard.ini" ]; then
		printf "\nPrevious configuration file found, sickbeard can try to use this file so you keep your settings\n"
              while true; do
    			read -p "Do you want to use the old configuration file? (yes/no) " yn
    			case $yn in
        			[Yy]* ) mv /usr/local/etc/sickbeard/sickbeard.ini /usr/local/etc/sickbeard/sickbeard.reuse; 
					break;;
        			[Nn]* ) mv /usr/local/etc/sickbeard/sickbeard.ini /usr/local/etc/sickbeard/sickbeard.old; 
					break;;
        			* ) echo "Please answer yes or no.";;
    			esac
		done
	fi

fi
